### PR TITLE
package.json

### PR DESCRIPTION
**Pull request by gcorreaalves**
Create package.json to be able install with npm.

### CODE REVIEW

**Comment by migstopheles** [comment]
@danielcrisp this would be excellent to have :)

**Comment by wescopeland** [comment]
@migstopheles Any plans to merge this and put the package on npm..?

**Comment by wescopeland** [comment]
@danielcrisp Any plans to merge this and put the package on npm?

**Comment by danielcrisp** [comment]
No, this project is no longer maintained so I'm reluctant to put it on npm

Feel free to fork it though and publish it yourself if you like

**Comment by migstopheles** [comment]
@danielcrisp @wescopeland I forked the repo and published to npm - https://www.npmjs.com/package/angular-rangeslider

**Comment by danielcrisp** [comment]
Thanks Mike

**Pull request closed without merging**
